# Problem 1 

In [1]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
a = np.array([3,9,5,15,12])
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
a.sort()
a

array([ 3,  5,  9, 12, 15])

# Problem 2

In [22]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
b = np.array([10,15,30,45,60])
print(b)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
c = np.arange(5,15)
print(c)
 
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
d = np.arange(50,100,5)
print(d)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
e = np.zeros(10)
print(e)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
f =np.ones(10)
print(f)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
g = np.linspace(0,100,5)
print(g)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
h = np.random.randint(10,30,size=5)
print(h)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
i = np.random.uniform(-1,1,size=10)
print(i)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
j = np.random.randint(10,50,size=(3,5))
print(j)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
print(j.sum(axis=0))
print(j.sum(axis=1))

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print(j.max())
print(j.min())
print(j.mean())

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
print(j.argmax())

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
k = np.arange(10,20)
print(k[:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(k[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print(j[0])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(j[1,2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(j[:,0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(j**2)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
l = np.random.randint(-50, 50, size=(3,5))
print((l > 0 ) & (l % 2 == 0))


[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[18 22 12 28 25]
[-0.65750122  0.55575955 -0.58709795  0.71606105 -0.68479855  0.01138936
 -0.74481583 -0.89249291 -0.72825634  0.09822599]
[[39 33 34 31 21]
 [10 20 41 42 24]
 [32 32 22 37 34]]
[ 81  85  97 110  79]
[158 137 157]
42
10
30.133333333333333
8
[10 11 12]
[19 18 17 16 15 14 13 12 11 10]
[39 33 34 31 21]
41
[39 10 32]
[[1521 1089 1156  961  441]
 [ 100  400 1681 1764  576]
 [1024 1024  484 1369 1156]]
[[False False False  True  True]
 [False False False False False]
 [False  True False False False]]
