# Problem 1

In [16]:
# 1 - numpy kütüphanesini import edin
import numpy as np 

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
a = np.random.randint(0,10,size=5)
print(a)
# 3 - matris'in boyutunu öğrenin
print(a.ndim)
# 4 - matris'i yeniden boyutlandırın
print(a.reshape(5,1))
# 5 - matris'in boyut sayısını öğrenin
print(a.size)

[5 2 0 0 4]
1
[[5]
 [2]
 [0]
 [0]
 [4]]
5


# Problem 2

In [15]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
x = np.arange(1,11,2)
print(x)

# 2 - Oluşturduğunuz matrisi parçalayın
y,z,q = np.split(x,[2,3])
print(y)
print(z)
print(q)

# 3 - Parçalanmış matrisleri birleştirin
print(np.concatenate([y,z,q]))


[1 3 5 7 9]
[1 3]
[5]
[7 9]
[1 3 5 7 9]


# Problem 3

In [24]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
i = np.random.randint(5,100,size=10)
print(i)

# 2 - matris'in özelliklerini inceleyin
print(i.ndim)
print(i.shape)
print(i.size)
print(i.dtype)


[96 96 87 62  8 58 19 12 96 56]
1
(10,)
10
int32
